:whale:

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,14 +23,14 @@ jobs:
                 POSTGRES_DB: flask_db_test
                 POSTGRES_PASSWORD: somePwd
         steps:
-          - checkout   
+          - checkout
           - run:
-              name: Install Python deps and initialise flask 
+              name: Install Python deps and initialise flask
               command: |
                   python3 -m venv venv
                   . venv/bin/activate
-                  pip install -r requirements/dev.txt 
-                  flask db upgrade    
+                  pip install -r requirements/dev.txt
+                  flask db upgrade
                   flask test
 
     dockerB&P:
@@ -59,3 +59,12 @@ jobs:
           - run:
               name: Deploy Master to Heroku
               command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
+
+          - run:
+              name: Test
+              command: |
+                  #HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+                  if [ "$HTTPCODE" -ne 200 ];then
+                      echo "heroku app not responding, failing deploy"
+                      exit 1
+                  fi
